### ISSUE TITLE
After Installation the dashboard show different msg error permission denied.

### ISSUE THREAD

**Issue by daebak74** [YunoHost-Apps/zabbix_ynh#12]
Hi,
thanks for your work to add this beautiful app in yunohost. I am new in Yunohost so I just installed with the latest release. No any error during the installation or with other app but when I visit Zabbix app I have this error msg. Please see the screenshot.

Is an app problem or I miss something in configuration ?

Thanks.

![zabbix_server_Dashboard](https://user-images.githubusercontent.com/11459528/85367563-29a6a200-b532-11ea-98a0-66562a36aca6.png)

**Comment by Mickael-Martin** [comment]
Have you an issue with your file system, like ReadOnly ? 
`ls -ail /var/lib/php/`

**Comment by Mickael-Martin** [comment]
no update, I close.
