### ISSUE TITLE
Upgrade to Yunohost 4.0 failed

### ISSUE THREAD

**Issue by Mickael-Martin** [YunoHost-Apps/zabbix_ynh#13]
Hello,

You cannot upgrade the last version of Yunohost if Zabbix is installed. I try to fix it.

**Comment by Jaxom99** [comment]
Ow, I wish I saw that :/ I launched the upgrade, and it broke the mysql config. Do you have any insight on what to fix ? I can provide logs of my VM if needed...

**Comment by Mickael-Martin** [comment]
Hello, can you repair your instance with uninstalling zabbix package ?

**Comment by Jaxom99** [comment]
Err, my instance is only running zabbix : the system is well, ynh web interfaces are OK. So I don't know what could be "repaired". I'm doing a remove-restore to see what happens, but I guess I should (re)run a ynh- migration inbetween (when zabbix app is absent)...

**Comment by Jaxom99** [comment]
:fearful: Aaaand the backup was faulty xS turns out zabbix app was never backuped, and the logs say :
```
Collecting files to be backed up for zabbix...
Backup /var/www/zabbix conf/zabbix.conf.php
Backup /etc/zabbix/web
[Error] Destination path 'etc/zabbix/web' already exist
Could not back up zabbix
Creating a backup archive from the collected files...
Backup created
name: auto-2021-01-28-apps
results: 
  apps: 
    adminer: Success
    rainloop: Success
    zabbix: Error
  system: 
size: 18142161
```
So I'm up for a fresh install, see if it works. Good thing I only have 3 hosts on it, sad to loose history though.

**Comment by yalh76** [comment]
Should be good now
