### ISSUE TITLE
App using rm -rf that was unspotted so far ... to be reported as error by the linter

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/zabbix_ynh#16]
c.f. https://github.com/YunoHost/package_linter/commit/4b513b4cd67275dfc597d30ddbfe1801293ad15a#diff-661c3b5fe67e77caea903b5fdb903b5fb6e8277c912d4a4af94e179ade2910baR1019

This app is using some `rm -rf` or similar command that was unspotted so far ... The app is gonna be capped to level 4 by the CI until this is fixed :/

**Comment by Mickael-Martin** [comment]
done.

**Comment by alexAubin** [comment]
Cheers !

The app is now apparently back to level 7 :+1: 

https://ci-apps.yunohost.org/ci/job/247

Though please note that the linter is reporting important warnings that should be taken care of at some point

**Comment by Mickael-Martin** [comment]
Yes, I know. I have planned to clean my code but I didn't like the post https://forum.yunohost.org/t/why-i-do-think-respecting-closely-the-template-is-really-important/11188 (and it is my answer : https://forum.yunohost.org/t/why-i-do-think-respecting-closely-the-template-is-really-important/11188/9). Since this post, I lost part of my motivation.

**Comment by alexAubin** [comment]
Ugh yeah very sorry about the stupid drama

I dunno what vision of the packaging you have right now ... I think since then we settled to say that many things in the current packaging format are a bit clumsy and super time-consuming and generally "not fun™" (like you say, copypasting the same old stuff etc...). Still we try to stick to a few common default practices which may or may not be super elegant, but allow for easy contribution from many people across the app ecosystem, and for example allow to have tools like the linter that perform static analysis to identify inconsistencies or security issues.

Anyway there's clearly stuff to be done to improve and simplify app packager's life. In particular : 
- on the short term the linter is being improved
- we have a new ynh_add_config helper that should come with 4.1, and starting from 4.2 i hope to generalize its usage. It should simplify a bit all the conf template management (ideally, get rid of all the bunch of lines with ynh_replace_string all over the place)
- on the mid-term (i hope for 4.2 or 4.3) there are plans to introduce [a new format for the manifest](https://github.com/YunoHost/issues/issues/1614) for better integration and declarativeness of a few things

Though overwall, this doesn't rework the packaging format paradigm .. but there are more long-term thoughts for a new packaging format being discussed here : https://github.com/YunoHost/issues/issues/1606 - tryign to move towards a more declarative format, which should help with "not duplicating code all over the place" and focusing on the actual app's logic than all the bureaucratic stuff of "checking the install path is available" and other "setting get/set"...  Still this is a complicated topic because of "how do we manage the legacy apps", having a good tradeoff between constrains and flexibility for special cases, having a good tradeoff between too-magic and too-verbose.

Soooo sorry again about the drama, and thank you for your hard work - just know that I generally share your feeling and concerns about packaging format, hopefully we can improve the whole thing over time and it's work-in-progress :s Feel free to come say hi on the chat (maybe you already did, sorry if I forgot, so many peoples!) - we have memes and emojis, and hopefully I can offer you a beer (or other favourite beverages :eyes: ) one of these days :+1: :green_heart:
