### ISSUE TITLE
Bullseye install fails : custom apt/deb repo not supporting bullseye

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/zabbix_ynh#21]
`'http://repo.zabbix.com/zabbix/4.4/debian bullseye Release' does not have a Release file`

**Comment by yalh76** [comment]
I look at that, but there is more of just that, there are also:

```
The following packages have unmet dependencies:
 zabbix-frontend-php : Depends: php-mysql but it is not going to be installed or
                                php-pgsql
                       Depends: fonts-dejavu but it is not going to be installed or
                                ttf-dejavu-core but it is not installable or
                                ttf-japanese-gothic but it is not installable
 zabbix-server-mysql : Depends: libevent-2.1-6 (>= 2.1.8-stable) but it is not installable
                       Depends: libsnmp30 (>= 5.7.3+dfsg) but it is not installable
                       Depends: libssh-4 (>= 0.8.0) but it is not going to be installed
                       Recommends: snmpd but it is not going to be installed
```
better to wait for a zabbix bullseye release

**Comment by mururoa** [comment]
Maybe head for 6.0. Still in alpha but :
- machine learning and many improvements (over 5.x)
- LTS so valid for 5 years. 5.4 will be deprecated in 14 months, 5.6 18 months after it's out.
- should be available this quarter. 5.6 should be available later; no date.
- But ... much more work to package 6.0 over 5.4 ? I'm not a developer but a sysadmin and can help for testing.
