### ISSUE TITLE
'duplicate log entry'  return by cron every day

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/zabbix_ynh#5]
Hi all, 
thx for your work, i love zabbix on my ynh server \o/

the issue : each day cron send me this message : 
```
/etc/cron.daily/logrotate:
error: zabbix-agent:1 duplicate log entry for /var/log/zabbix/zabbix_agentd.log
error: zabbix-server-mysql:1 duplicate log entry for /var/log/zabbix/zabbix_server.log
```
could you explain me please what i should do ?
Thx, 
isAAAc

**Comment by Mickael-Martin** [comment]
Hi @isAAAc , thanks for you return. I think I'm duplicate the log rotate in my install script.
Can you repair the vagrant box file please ? I rebuilt my tests environment and https://build.yunohost.org/yunohost-stretch-unstable.box not exists (I install the iso file actually)

**Comment by isAAAc** [comment]
"Can you repair the vagrant box file please" 
i don't know how to to this :/

**Comment by Mickael-Martin** [comment]
Try to upgrade, I think it's ok.
Normaly, the file /etc/logrotate.d/zabbix has been deleted by the upgrade, still only zabbix-server and zabbix-agent configuration file (native).

**Comment by isAAAc** [comment]
yunohost app upgrade zabbix    tells me zabbix is already up to date

**Comment by Mickael-Martin** [comment]
can you print the return of `ls /etc/logrotate.d/zabbix*` please ?

**Comment by isAAAc** [comment]
```
ls /etc/logrotate.d/zabbix*
/etc/logrotate.d/zabbix  /etc/logrotate.d/zabbix-agent  /etc/logrotate.d/zabbix-server-mysql
```

**Comment by Mickael-Martin** [comment]
OK, I see. The community list is not up to date, and not include my correction and the upgrade to the version 4.0.4-1 of Zabbix. Please wait the new build (I don't know when...) or remove manually the /etc/logrotate.d/zabbix file.

**Comment by isAAAc** [comment]
no pb ;) i'll wait few days and i'll give you a feedback after the next upgrade :)

statuts : pending

**Comment by Mickael-Martin** [comment]
The update fixes the issue for me. Can you try to upgrade ?
Moreover, the Zabbix trusted (tested for Yunohost) version raise to 4.0.4 normally.

**Comment by isAAAc** [comment]
after upgrade : 
```
/home/jps/tools/debian-handbook.pdf
/home/jps/tools/debian-handbook-fr.pdf
```
should be ok 
thx very much !

i close for now, i'll repoen if i get a new warning mail tomorow morning ;)

**Comment by Mickael-Martin** [comment]
> /home/jps/tools/debian-handbook.pdf
> /home/jps/tools/debian-handbook-fr.pdf
I don't understand this result... ??? 


> i close for now, i'll repoen if i get a new warning mail tomorow morning ;)
OK !

**Comment by isAAAc** [comment]
my bad, wrong cp :/ 
edtied comment, sry for the noise

**Comment by Mickael-Martin** [comment]
I edited the quote. Bye !

**Comment by Mickael-Martin** [comment]
Just for your information, I removed this duplicate conf in backup/restore files. I push the version 1.2.1 with this patch.
