### ISSUE TITLE
Please consider using ynh_install_extra_repo

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/zabbix_ynh#6]
Hi

We noticed that you use an extra repository for your app. Using extra repository without pinning it can have consequences.
Please consider using the experimental helper [ynh_install_extra_repo](https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/ynh_add_secure_repos/ynh_add_secure_repos__2) to handle securely any extra repo.

If you encounter any problem using this helper, please open an issue on the repo.

PS: Also, do not add the nonfree repo without clearly asking to the user if he agree to do so.

**Comment by Mickael-Martin** [comment]
I commit my futur v2 this week. In this version, I remove the usage of non-free repo.
I will patch my v2 to add your helper. Thanks.

**Comment by Mickael-Martin** [comment]
Hi,
I have looking to change my way to add the repo zabbix but actually I cannot : 

1. I don't have an official URL with the gpg key in binary format. The gpg file in hexa format not work (official url : https://repo.zabbix.com/zabbix-official-repo.key )
2. If I use "apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 082AB56BA14FE591", it's ok but the helper don't use this method. (or wget -O - http://repo.zabbix.com/zabbix-official-repo.key|apt-key add - )

Moreover, I use the official way to install Zabbix repo (cf : https://www.zabbix.com/documentation/4.0/manual/installation/install_from_packages/debian_ubuntu ).
So, if you have a suggestion, I can try, but I don't have solution today.

**Comment by maniackcrudelis** [comment]
Hum, in this link the recommended way is to download the deb file and install it manually...

This helper doesn't expect a binary key, just a key.
`apt-key` is deprecated, so we use the directory to store the key.
If you can find a way to add the key to this directory in a different way, we can explore ways to fix the helper.

**Comment by Mickael-Martin** [comment]
`curl https://repo.zabbix.com/zabbix-official-repo.key | gpg --dearmor > /etc/apt/trusted.gpg.d/zabbix-official-repo.gpg`
works. Please add option to use gpg --dearmor in pipeline.
I still open this issue for the moment.

**Comment by maniackcrudelis** [comment]
We were about to use it for all keys
https://github.com/YunoHost-Apps/Experimental_helpers/issues/34

**Comment by Mickael-Martin** [comment]
Ok for the RC2.0 https://github.com/YunoHost-Apps/zabbix_ynh/blob/98f14236cffb00dafe88981e5ff9ae563e4cca98/scripts/_common.sh#L171
Actually in Package_check process

**Comment by Mickael-Martin** [comment]
done !
