### ISSUE TITLE
installation difficulties

### ISSUE THREAD

**Issue by arnoudspammer** [YunoHost-Apps/zabbix_ynh#7]
hi it seems i can't install zabbix just yet. Here is the log

https://paste.yunohost.org/raw/vezizuvuwu

Thank you in advance for your time

**Comment by Mickael-Martin** [comment]
Hi, I push my v2 today in the community list. Try again after the update. 
I notify you when it's availaible.

**Comment by Mickael-Martin** [comment]
ok, sorry for my very late answer, I published a new version with a correct installation. I work again on my v2 to add bests practices.
Can you try ?

**Comment by Mickael-Martin** [comment]
Now, you can try RC2.0 branch if you want.

**Comment by Mickael-Martin** [comment]
Can you try with the new package ?

**Comment by Mickael-Martin** [comment]
no update, I close.
