### ISSUE TITLE
is update/upgrade failing ?

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/zabbix_ynh#8]
hi, 

when i update/upgrade ynh, zabbix (server and frontend) is announced to be upgraded, but nothing happens

there is the prompt backlog : 

https://krashboyz.org/zerobin/?8ae4097145ec2580#2kKpzywltlH6xgfQTHNRJnxSjdEWUjwaaFMfrG56zNw=

a friend has the same trouble too, 
i think something is borken no ?

thx for your help and your work ;)

isAAAc

**Comment by martoni35** [comment]
Hello,

I've got the same issue...

martoni

**Comment by Mickael-Martin** [comment]
Hi,
I try to patch the future package. I work on it. Sorry for the inconvenient.

**Comment by Mickael-Martin** [comment]
Now, you can try RC2.0 branch if you want.

**Comment by Mickael-Martin** [comment]
no update, I close.
